language: java
jdk:
- oraclejdk8
services:
- docker
install:
- true
addons:
  ssh_known_hosts: 140.143.154.41
script:
- mvn install
- docker build -t qinlikang/wechat .
- bash docker_push.sh
- ssh root@140.143.154.41 "mkdir -p /opt/wechat"
- scp ./restart.sh root@140.143.154.41:/opt/wechat/
- ssh root@140.143.154.41 "docker pull qinlikang/wechat; cd /opt/wechat; bash restart.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_82f3d63fc4b9_key -iv $encrypted_82f3d63fc4b9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
env:
  global:
  - secure: n3+9MxMfZgMBlndPRAKVGyt0SnCZBl4WleWiU8m8mZoxrkVq5S6P1J8uGzTqFyvF1kdpSUFZm2Jm+ddulf54pZW2WHQ/YbLPZhtBYb/x39+lq9PmvNAjchBJyasMDnIZoL6NNZBnEG6wfF5MNcqVqbMpgEf38NwOjdNIHVRm2/9Npei88E3CTSbgkA6dy18DcMnLSkVGhLz/R5s8YDp5YepKUjT1khD+FFiYgPmezoXqx6XHpaB2VYIwMUGYQp8WaGyOMCqLHshNBDLKFWAjw846SetTAie9cskwUP+cCW5dbvgRFkXA9rC5RJRvf41V77C7iZ532oRPcoy5/813mIVRkddRlPCnSsjagjqK+re4/WfLFHKEOa0h6Dc/NI1T1r9+o6a0gCFTU+2eZXzfqxtBHOkIHmPB4r8HK5Zqqo0mx4zXu+yziC7FFr1Fs3xw/oAW4BJCR0Rbo+JtmlQRBtc/4KXxA/PWF7/7ndsSVH9FTxrbSTZwnkHb4dRUN33FYTp0dVYGh0LNh3HiFXCw7nRjUgy5/X/ZzMlhuWZzVF+lLQvaVJAGH4PBaDQyWHLttZmIvraxICpBGhkeZVrLhqMZJMB+aKQF0vn4VEDDQjtqg+jsR/EvClm+s5kF76L2FY20SVlg5EfQ3kdzWizgx77xrFR7w5Xnyw0HHGV7yV0=
  - secure: pEW2NiShy3PSuKzgdoDebuvg+5KJMr0JiBMSxPec9jgnVwTahemby+lTTMa+4glxTeIWSVkQYU4tpgAqDm3yBi0NQXK1S2Nzw71hmwEwj1/QMSgg8rJxCQVN56aETVzwnk49wiSlFjohvY1lSb+wCH3+eq8Q5vg0R/TZzbiaW5kiQ9d3q89JJ1CGJs8F8IzbKbrnXKVBoQyMOFqziEPs0nouJhz4x/n7MeF8ic92gSxXaaFbr5+15RuW8/9Q0bBZqcjnQ6xgByWO9nzDy5FC4rqH7h6/4w2jvZAaw/r54k/ns8JC0PhOkzI9nLSzTZpNxaszRjDxkvng+pVaNbb0Azjr691rnRWOhqN/xDmE5GEHuke6HnUAJkgOpPw90rDdiHG0/u4j3hDoOUewFZODMvQMXQLKhMpmiXzfQ9bbutjuZdyOAQh2XjdMpFDLRrwdm5vM40QY0Sq65NKUOtvdTBzRDeGe9DQQQBfHjs0+g7hj7HVD6sOcOYth0493egG3ijdBEYynK85h4Wr3QmGwt3JSZmBBMMW+8KCu/wHxndQDJLFWy6Fi0IQxShd/otESCz3/b05S6BY1h04nODijOBGOsChtir8jPtNnek0JqwSBem6HCofKU1xq/7xfEXxAgviCkrEFlF48/f2cQ+Cy1K2PDWz11V2GRvZVPsORkbU=
